# Generated by Django 5.2.7 on 2025-10-21 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_migrate_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
